stages:
  - build
  - deploy

build-docker-image:
  services:
    - docker:20.10.16-dind
  image: ubuntu
  stage: build
  before_script:
    - . ./install_aws_cli.sh
    - docker info
  script:
    - echo "$(git log -1)"
    - docker build -t baseforci .
